In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']


One Hot Representation

In [14]:

### Vocabulary size
voc_size=10000
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[7294, 5239, 6179, 583], [7294, 5239, 6179, 5596], [7294, 5921, 6179, 8108], [5438, 8875, 5464, 2613, 4890], [5438, 8875, 5464, 2613, 219], [7019, 7294, 4807, 6179, 8523], [8881, 1646, 686, 2613]]



Word Embedding Represntation

In [17]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7294 5239 6179  583]
 [   0    0    0    0 7294 5239 6179 5596]
 [   0    0    0    0 7294 5921 6179 8108]
 [   0    0    0 5438 8875 5464 2613 4890]
 [   0    0    0 5438 8875 5464 2613  219]
 [   0    0    0 7019 7294 4807 6179 8523]
 [   0    0    0    0 8881 1646  686 2613]]


In [18]:
dim =10

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:

print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step
[[[-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007
    0.04237891 -0.03204595  0.02377912  0.02915496 -0.02696991]
  [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007
    0.04237891 -0.03204595  0.02377912  0.02915496 -0.02696991]
  [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007
    0.04237891 -0.03204595  0.02377912  0.02915496 -0.02696991]
  [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007
    0.04237891 -0.03204595  0.02377912  0.02915496 -0.02696991]
  [-0.04566219 -0.03959876 -0.00021698 -0.01998237  0.03708133
    0.01218698  0.01884386  0.04468106  0.04471597  0.01099389]
  [-0.0131328  -0.04810911 -0.03560724  0.03406132 -0.00723598
    0.01264379 -0.02839137  0.00916133  0.01952438 -0.03833755]
  [-0.03009601 -0.04308486  0.03925676 -0.04665846  0.01528848
    0.0169647  -0.00572751  0.04552138  0.04287959  0.02306434]
  [ 0.02897331 -0.043222    0.00720923 -0.02636477  0.0431756
   -0.0078

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 7294, 5239, 6179,  583], dtype=int32)

In [21]:

print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007  0.04237891
  -0.03204595  0.02377912  0.02915496 -0.02696991]
 [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007  0.04237891
  -0.03204595  0.02377912  0.02915496 -0.02696991]
 [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007  0.04237891
  -0.03204595  0.02377912  0.02915496 -0.02696991]
 [-0.02088816  0.0240881  -0.04812317  0.04572108 -0.03808007  0.04237891
  -0.03204595  0.02377912  0.02915496 -0.02696991]
 [-0.04566219 -0.03959876 -0.00021698 -0.01998237  0.03708133  0.01218698
   0.01884386  0.04468106  0.04471597  0.01099389]
 [-0.0131328  -0.04810911 -0.03560724  0.03406132 -0.00723598  0.01264379
  -0.02839137  0.00916133  0.01952438 -0.03833755]
 [-0.03009601 -0.04308486  0.03925676 -0.04665846  0.01528848  0.0169647
  -0.00572751  0.04552138  0.04287959  0.02306434]
 [ 0.02897331 -0.043222    0.00720923 -0.02636477  0.0431756  -0.00788406
  -0.04731464 