In [6]:
import numpy as np


1. ReLU - Rectified Linear Unit (Hidden Layer)

In [7]:
def relu(x):
    return np.maximum(0,x)

In [8]:
relu(10)

10

In [9]:
relu(-10)

0

2. Leaky ReLU (Hidden Layer)

In [12]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)


In [13]:

leaky_relu(-1)

array(-0.01)

In [17]:

leaky_relu(np.array([-1, 0, 1, 2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

3. ELU - Exponential Linear Unit (Hidden Layer)
   
ELU has a small slope for negative values, unlike ReLU, to avoid the dying ReLU problem.

In [18]:
def elu(x, alpha=1.0):
    return np.where(x>0, x, alpha * (np.exp(x) - 1))


elu(5)

array(5.)

In [19]:
elu(np.array([-1, 0, 1,2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

4. Sigmoid (Output Layer & Binaryclass Problem)

In [20]:
def sigmoid(x):
    return  1 / (1+np.exp(-x))

In [21]:
sigmoid(np.array([-1,0,1,2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

5. Softmax (Output Layer & Multiclass Problem)

In [22]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [23]:
proba = softmax(np.array([-1, 0,1, 2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [24]:
sum(proba)

1.0

6. Swish (Hidden Layer)

In [25]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)


In [26]:
swish(5)

4.966535745378576

In [28]:
swish(-1)

-0.2689414213699951

In [27]:

swish(np.array([-1, 0, 1, 2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

7. Linear (Output Layer)

In [29]:
def linear(x):
    return x



In [30]:
linear(10)

10

8. Tanh (Hyperbolic Tangent)

In [31]:
def tanh(x):
    return np.tanh(x)

In [32]:
tanh(10)

0.9999999958776927

In [33]:
tanh([-1, 0, 1, 2])


array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [40]:
import math


In [41]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [43]:
tanh(-1)

-0.7615941559557649